[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.79.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.gh-pages] # 'gh-pages' is a branch name
command = "echo 'gh-pages'"
publish = "."