on:
  push:
    branches:
      - gha

name: build-site

jobs:
  hugo:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages("blogdown")
          blogdown::install_theme(theme="hugo-apero/hugo-apero", force=TRUE)
        shell: Rscript {0}

      - name: Build website
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'blogdown::build_site()'
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch